apiVersion: apps/v1
kind: Deployment
metadata:
  name: attribute-prediction
  namespace: cs-25-sw-5-06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attribute-prediction
  template:
    metadata:
      labels:
        app: attribute-prediction
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/astep-aau/attribute-prediction:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "cluster"
        - name: DEBUG
          value: "false"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
