apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cs-25-sw-5-06
type: Opaque
stringData:
  # TODO: Replace with actual database credentials
  DATABASE_URL: "postgresql+asyncpg://USERNAME:PASSWORD@SERVER:PORT/DATABASE"
