apiVersion: v1
kind: Service
metadata:
  name: attribute-prediction-service
  namespace: cs-25-sw-5-06
spec:
  selector:
    app: attribute-prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
